name:                laop-benchmarks
version:             0.1.0.0
github:              "bolt12/laop-benchmarks"
license:             BSD3
author:              "Armando Santos"
maintainer:          "armandoifsantos@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bolt12/laop-benchmarks#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  laop-benchmarks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -funfolding-use-threshold=16
    - -fexcess-precision # Good for doubles
    - -optc-O3 # Good for doubles
    - -optc-ffast-math # Good for doubles
    - -O2
    dependencies:
    - laop-benchmarks
    - laop
    - matrix
    - hmatrix
    - linear
    - vector
    - criterion
    - deepseq
    - QuickCheck

tests:
  laop-benchmarks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - laop-benchmarks
